### ISSUE TITLE
Completely black video output

### ISSUE THREAD

**Issue by hdawod** [v8hid/infinite-zoom-automatic1111-webui#105]
**Describe the bug**
after generating the video it shows completely black. Sometimes shows the first scene followed by black frames

**To Reproduce**
1. I used the default prompts for infinite zoom.  
2. choose Realistic_Vision_V1.4-inpainting.ckpt
3. check "Apply color correction to img2img results to match original colors."
4. SD VAE "Automatic"
5. Clip skip "1"
6. all other settings left as default. 

**Expected behavior**
I suspect low VRAM

**Screenshots of error**
here is a sample
https://youtube.com/shorts/4Le4B5F7bEQ?feature=share
https://youtube.com/shorts/ACLTt7SU8oc?feature=share

**Desktop (please complete the following information):**
 - Win10
 - Laptop AMD RYZEN7 5000 series, AMD Radon RX, 16Mb RAM

**Comment by v8hid** [comment]
Hello @hdawod,
Try to change your sampler to Euler A

**Comment by hdawod** [comment]
> Hello @hdawod, Try to change your sampler to Euler A

It works, thank you so much.

**Comment by hdawod** [comment]
> Hello @hdawod, Try to change your sampler to Euler A

Is it normal to lose colors by the end of the video?
eg.
https://youtube.com/shorts/MGx0w9zWi6Q?feature=share

**Comment by hdawod** [comment]
> > Hello @hdawod, Try to change your sampler to Euler A
> 
> Is it normal to lose colors by the end of the video? eg. https://youtube.com/shorts/MGx0w9zWi6Q?feature=share

I found the solution by untick/deactivate the option "Apply color correction to img2img results to match original colors."
