### ISSUE TITLE
todo: add Settings, slider for out size, use custom outpath

### ISSUE THREAD

**Issue by GeorgLegato** [v8hid/infinite-zoom-automatic1111-webui#11]
Assigning to me. to avoid races or concurrent implementations

**Comment by v8hid** [comment]
Hello @GeorgLegato, I'm interested in learning more about the features you're looking to add to the project. I have a list of potential features and would welcome your input. If you're interested in contributing, I can add you to the project.

In order to communicate more directly, could you please let me know how I can reach you? Thank you!

**Comment by GeorgLegato** [comment]
nothing special. just to extend stuff, like
ratio support, not only squared
I havent yet understood completely how the process is, so i need a bit to investigate
put me to your project, communication here is fine

**Comment by GeorgLegato** [comment]
One feature for 360 panorama movies is to end the video on the last frame, forevery. So tha zoom in/out of the movie can be still viewed interactively in the 360 sphere.

**Comment by GeorgLegato** [comment]
@v8hid I would like to create such videos:
https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-video.html#example

**Comment by v8hid** [comment]
There are a few issues that we should consider:

1. The program is currently designed to process images with aspect ratios of 1:1. We should verify if the program should be updated to handle other aspect ratios as well.

2. If you want to change the resolution, you will need to modify the `mask_with` variable accordingly.

3. If we want to add a button for sending images to another extension, we should check if the user has that extension installed before showing the button.

**Comment by GeorgLegato** [comment]
1) yes, thats why first the slider tweaks both x and y
2) i ll check 
3 the sendto button is already in my extension. so my extension is installed and adds this button.

**Comment by GeorgLegato** [comment]
2) howto calculate mask_width? just output_size/2?

**Comment by v8hid** [comment]
> 2. howto calculate mask_width? just output_size/2?

it should be less than `image_width / 2`, the optimal result might be `image_width / 4`

**Comment by GeorgLegato** [comment]
video size is always 512, because the size of frames is not used for writing, see video.py line 17 "w,h" unsused

**Comment by v8hid** [comment]
> video size is always 512, because the size of frames is not used for writing, see video.py line 17 "w,h" unsused

Right thank you, I need to refactor the code soon :))

**Comment by GeorgLegato** [comment]
> > video size is always 512, because the size of frames is not used for writing, see video.py line 17 "w,h" unsused
> 
> Right thank you, I need to refactor the code soon :))

I have disabled the w,h variables. the writer is not to be set explicetely, driven by input frame size and that block size
