### ISSUE TITLE
[BUG] A1111 1.8.0 upgrade breaks the extension

### ISSUE THREAD

**Issue by webmadmangit** [v8hid/infinite-zoom-automatic1111-webui#118]
After upgrading Automatic1111 to version 1.8.0, this extension, and a couple of others, throw the same error.

>' *** Error executing callback ui_tabs_callback for /home/numcrunch/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py
    Traceback (most recent call last):
      File "/home/numcrunch/stable-diffusion-webui/modules/script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File "/home/numcrunch/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/iz_helpers/ui.py", line 254, in on_ui_tabs
        (
    TypeError: cannot unpack non-iterable OutputPanel object

---
'

The other extensions I'm getting this error with are Deform and SadTalker.

**Comment by RobeSantoro** [comment]
@webmadmangit Just figured out why it was broken and patched it in this PR: 
https://github.com/v8hid/infinite-zoom-automatic1111-webui/pull/119

**Comment by jonbecker** [comment]
> @webmadmangit Just figured out why it was broken and patched it in this PR: #119

patched mine with that and can confirm it worked, thanks

**Comment by webmadmangit** [comment]
Works like a charm! Thanks so much.
