### ISSUE TITLE
[Feature] Sampler Selection Field

### ISSUE THREAD

**Issue by v8hid** [v8hid/infinite-zoom-automatic1111-webui#14]
Users can now choose their desired sampler from the main settings page with our new Sampler Selection Field.
p.s: now it uses `Euler A`

**Comment by jet3004** [comment]
Sweet! Great work on this and, seriously, way to keep it simply. Would love to see: simple rotation option, simple drag n drop audio track option so we can throw on a .mp3/.aac for a small soundtrack on the export.

A bit more creative but a really cool thing would be (simple, ha) ChatGPT API key plugin where I can just have it fill in both frame number + prompt row, either entirely from nothing or perhaps just 'picking up' from whatever your first prompt says. Haven't seen too many straightforward ChatGPT/OpenAI API key implementations in SD plugins but could work so well.

**Comment by v8hid** [comment]
Hi @jet3004,

Thank you for your valuable input and suggestions. Your ideas are great and align with our long-term goals. However, currently, we are occupied with more pressing features that need to be implemented first. I suggest you write your idea in the Discussion section, where it can be reviewed and prioritized at the right time.
