### ISSUE TITLE
Error message in console, but generation still works.

### ISSUE THREAD

**Issue by BlastedRemnants** [v8hid/infinite-zoom-automatic1111-webui#18]
Hi, and thanks for the cool extension! I figured I'd let you know that I've been getting an error message in the console on every run regardless of settings, and it's been persisting through the recent updates. The error doesn't seem to actually hurt anything as far as I can tell, but I don't know hardly anything about Python so all I can see in the error message is that it looks like SD is trying to talk to my system Python, rather than my venv Python, but I have no idea really, sorry! In any case here's the error message copied from the console, it shows up after every generation when I use Infinite Zoom; 

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\blast\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\blast\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Edit: Forgot to add any relevant info, but if it helps I'm on the latest build of Auto's and I'm using the latest version of this extension as well. I've got a 2070 Super with 8 gigs, and if there's anything else that might help then please let me know, thanks!

**Comment by GeorgLegato** [comment]
i see that errors as well, even one cannot see it is pointing to our extension, it is raised just after rendering a zoom movie.
we will have an eye on it

**Comment by v8hid** [comment]
> cannot see it pointing to our extension

**Comment by v8hid** [comment]
@BlastedRemnants I don't know why You got this error, but as @GeorgLegato said the error is not pointing to our extension. Hoping you found a solution.

**Comment by BlastedRemnants** [comment]
> @BlastedRemnants I don't know why You got this error, but as @GeorgLegato said the error is not pointing to our extension. Hoping you found a solution.

Ah, I wasn't sure what George meant at first but I understand now, thanks. I have no idea why I get the error but like I said it doesn't seem to stop anything from working, I just assumed it was something to do with this extension because it only happens when I do an Infinite Zoom generation. I'll just ignore it I guess, doesn't seem to be hurting anything for me and I only mentioned it in case anyone else was having any trouble. Thanks tho, cheers!

**Comment by BlastedRemnants** [comment]
Sorry to keep coming back, but I was a bit premature when I said the error message was no longer happening. I do still get it, it just didn't happen the first time I tried after updating. In any case tho everything still works so I'm not worried about it, just seems strange that it's even talking to my system Python since I thought Auto's only used stuff in the venv. In any case thanks again for the cool extension and keep up the great work! Btw the new updates are awesome  :D
