### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Tobe2d** [v8hid/infinite-zoom-automatic1111-webui#21]
1 - Can we have frame size or aspect ratio? so we can have it 1:1 or 16:9 etc..

2 - Can we open up the duration Total Outpaint Steps over 100? something to be set by user
currently its maxed with 100.

**Comment by v8hid** [comment]
The first one is almost done,
And the second one is in progress.

**Comment by Tobe2d** [comment]
Awesome!
