### ISSUE TITLE
Store and Load prompts to/from file

### ISSUE THREAD

**Issue by GeorgLegato** [v8hid/infinite-zoom-automatic1111-webui#24]
to avoid rewriting prompts, have a
*save button
* load button
* and save that generation info next to the video like "infinite-zoom-1231556.txt"

Format: dont know, what the gradio table is able to read/write

**Comment by GeorgLegato** [comment]
nearly done. nice you can ask chatgpt to write long prompt stuff like:
![image](https://user-images.githubusercontent.com/7210708/232358906-cb7aed15-b35b-4d1b-bdb6-80f883dc312c.png)
![image](https://user-images.githubusercontent.com/7210708/232358951-67e85ff1-7d19-42bf-bd4e-a443c9f700fb.png)

**Comment by v8hid** [comment]
Great job, keep it up.
I have an idea to export all the settings at some point I will work on it as soon as I can.
