### ISSUE TITLE
What is purpose of the 1st prompt column actually?

### ISSUE THREAD

**Issue by GeorgLegato** [v8hid/infinite-zoom-automatic1111-webui#31]
I think it is not used in code and that intentionally, is it just a numbering?
@v8hid we could remove it, right?

**Comment by v8hid** [comment]
@GeorgLegato I didn't understand can you explained yourself?

**Comment by deklesen** [comment]
It is used to denote the inpainting step starting from which that prompt is used (until the end, or until it is replaced by another)

See the lines starting here: 
https://github.com/v8hid/infinite-zoom-automatic1111-webui/blob/2dc9497d7e3d680c36cdddc9900f64921e88da1d/scripts/infonite-zoom.py#L202

And then this line here:
https://github.com/v8hid/infinite-zoom-automatic1111-webui/blob/2dc9497d7e3d680c36cdddc9900f64921e88da1d/scripts/infonite-zoom.py#L263

**Comment by v8hid** [comment]
@GeorgLegato Let me give you an example:
Assume we want to do 3 prompts:

| step     | prompt   |
| -------  | -------- |
| 0 to 3   | prompt1  |
| 3 to 10  | prompt2  |
| 10 to 20 | prompt3  |

I don't see any better approaches than
0 => prompt1
3 => prompt2
10 => prompt3
