### ISSUE TITLE
Error Progress tracking requires queuing to be enabled

### ISSUE THREAD

**Issue by zboing** [v8hid/infinite-zoom-automatic1111-webui#32]
venv "stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 00dab8f10defbbda579a1bc89c8d4e972c58a20d
Installing requirements for Web UI
Installing requirements 1 for Infinite-Zoom

#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: 43ae9d55531004f1dedaea7ac2443e9b16739913
SD-WebUI revision: 00dab8f10defbbda579a1bc89c8d4e972c58a20d

Checking Dreambooth requirements...
[+] bitsandbytes version 0.35.0 installed.
[+] diffusers version 0.10.2 installed.
[+] transformers version 4.25.1 installed.
[+] xformers version 0.0.16rc425 installed.
[+] torch version 1.13.1+cu117 installed.
[+] torchvision version 0.14.1+cu117 installed.

#######################################################################################################

Launching Web UI with arguments: --xformers
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
SD-Webui API layer loaded
Loading weights [e6415c4892] from stable-diffusion-webui\models\Stable-diffusion\realisticVisionV20_v20.safetensors
Creating model from config: stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Model loaded in 6.4s (create model: 0.5s, apply weights to model: 1.1s, apply half(): 1.3s, load VAE: 1.2s, move model to device: 0.9s, load textual inversion embeddings: 1.2s).
Traceback (most recent call last):
  File "\stable-diffusion-webui\launch.py", line 361, in <module>
    start()
  File "\stable-diffusion-webui\launch.py", line 356, in start
    webui.webui()
  File "\stable-diffusion-webui\webui.py", line 202, in webui
    app, local_url, share_url = shared.demo.launch(
  File "\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1337, in launch
    raise ValueError("Progress tracking requires queuing to be enabled.")
ValueError: Progress tracking requires queuing to be enabled.
Press any key to continue . . .

**Comment by v8hid** [comment]
I know what is causing this error it's `gr.Progress()`,
I will fix it asap.

**Comment by v8hid** [comment]
@zboing Update and try again.

**Comment by zboing** [comment]
same behaviour @v8hid

**Comment by v8hid** [comment]
@zboing are you running the WebUI with this flag --no-gradio-queue ??

**Comment by zboing** [comment]
no, if I add it in the user bat it gives me this error: launch.py: error: unrecognized arguments: --no-gradio-queue

**Comment by FrozenWolf-Cyber** [comment]
Any updates on this?

**Comment by v8hid** [comment]
> Any updates on this?

It is fixed, the progress is not shown but you won't get any error.
