### ISSUE TITLE
install broke webui 

### ISSUE THREAD

**Issue by laurentopia** [v8hid/infinite-zoom-automatic1111-webui#33]
After following the simple install steps, now:
![image](https://user-images.githubusercontent.com/26075468/232896734-22a5dd49-7f70-4576-891a-9cab4b7356f8.png)

**Comment by stahlfest** [comment]
Same issue here...

**Comment by greenrocket77** [comment]
Same here since the last update. No issue with previous versions.

**Comment by v8hid** [comment]
@laurentopia @stahlfest @greenrocket77 Can you send the version of WebUI you are using ?
It is located in the footer as commit.

**Comment by greenrocket77** [comment]
> @laurentopia @stahlfest @greenrocket77 Can you send the version of WebUI you are using ? It is located in the footer as commit.

Commit : a9eab236d7e8afa4d6205127904a385b2c43bb24

I ran many tests and the last commit will provide no error during the launch but won't generate anything then. I had something related to an "index" error. Anyway, the last commit is full of bugs on my end so I would much prefer to stick on the one I mentioned!

ps: thank you for your work, that's an amazing extension.

pps: I created earlier [a ticket on the automatic1111 github](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9721) with more details, not knowing this was related to the extension.

**Comment by v8hid** [comment]
@greenrocket77 are you running the WebUI with this flag `--no-gradio-queue` ??

**Comment by greenrocket77** [comment]
> @greenrocket77 are you running the WebUI with this flag `--no-gradio-queue` ??

I tried to see if that would change anything but that resulted in this error during the launch : `launch.py: error: unrecognized arguments: --no-gradio-queue`

**Comment by stahlfest** [comment]
@v8hid Commit: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

I removed the 'infinite-zoom-automatic1111-webui' folder from the extension directory, followed by restarting the 'webui-user.bat' file, and everything functioned correctly without the extension.

However, upon reinstalling the 'infinite-zoom-automatic1111-webui', the same error reemerged.

**Comment by greenrocket77** [comment]
The bugfix did the job on my end after reinstalling the last version of the extension. Thank you.

**Comment by guijuzhejiang** [comment]
When do you plan to finish extension for faceid?
