### ISSUE TITLE
prompts and settings for one example

### ISSUE THREAD

**Issue by laurentopia** [v8hid/infinite-zoom-automatic1111-webui#36]
It would be nice to get a sense of how to get good results and what models do a good job.

**Comment by v8hid** [comment]
Hi @laurentopia  You can check out [Wiki - Inpainting models](https://github.com/v8hid/infinite-zoom-automatic1111-webui/wiki/Inpainting-models)

**Comment by laurentopia** [comment]
I read those, I learn better by example so what I meant by that is: show the prompts and screenshots of one of your examples. I can not get rid of the borders for example or get anywhere near your level of quality.
