### ISSUE TITLE
ValueError: All images in a movie should have same size

### ISSUE THREAD

**Issue by 2Suen** [v8hid/infinite-zoom-automatic1111-webui#38]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py", line 154, in create_zoom
    result = create_zoom_single(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py", line 357, in create_zoom_single
    write_video(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/iz_helpers/video.py", line 35, in write_video
    writer.append_data(np_frame)
  File "/usr/local/lib/python3.9/dist-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/usr/local/lib/python3.9/dist-packages/imageio/plugins/ffmpeg.py", line 591, in _append_data
    raise ValueError("All images in a movie should have same size")
ValueError: All images in a movie should have same size

**Comment by v8hid** [comment]
Could you share what Output Width and Height you used?

**Comment by jmsether** [comment]
I have this same exact error. I am using the default 512x512

**Comment by v8hid** [comment]
@jmsether send me the commit of your WebUI, you can find it at the bottom of your WebUI page.

**Comment by jmsether** [comment]
@v8hid says commit: [22bcc7be]

**Comment by v8hid** [comment]
@jmsether are you using a custom init image? If yes send your init image here. (drag it to text box)

**Comment by jmsether** [comment]
@v8hid I am not sure what that is. So I am going to say that I probably am not.

**Comment by JerryOver** [comment]
I am having a similar issue. Mine is: "All images in a movie should have same number of channels." This happens when I use a CUSTOM INITIAL IMAGE. I can get a infinite zoom video if I put no initial image there, but I really want to see the results of it.

**Comment by jmsether** [comment]
I just realized what was meant by custom init image. And no I am not using one. Should I be?

**Comment by v8hid** [comment]
@jmsether Are you getting this error every time or just sometimes?
What is your default Width and height in `webui setting` > `infinite zoom`

**Comment by v8hid** [comment]
@jmsether can you send the image you are using in discord server?

**Comment by jmsether** [comment]
@v8hid default is 512 x 512. And can you please elaborate on what you mean by image? I am not using any starting image.

**Comment by v8hid** [comment]
@jmsether wrong mention, is it happening every time or just sometimes?

**Comment by GeorgLegato** [comment]
I have tested develop version on dev branch. everything works fine, 512x512 or non-square resolution with and without upcaling.

**Comment by jmsether** [comment]
@v8hid No worries. It happens every time. I have tried both main and dev and it does not work on either.

**Comment by GeorgLegato** [comment]
Could be a rounding issue? if start image is lik 693x511, do we round up or down?.
to know it exactly we need to inspect the variable "all_frames[]" in the python script. we should add maybe an debug print on exception, to see all sizes and how they differ

**Comment by jmsether** [comment]
> 

Why round when we can crop to desired resolution? Would that not be a better solution? Course I have not dived through the code yet(I am not a Python fan) so I have no idea what's implemented. It could be cropping for all I know.

**Comment by GeorgLegato** [comment]
if you provide a start image it is being scaled. crop is another possibility, but not an provided option,yet. would be another button: scale policy on init image.
I add an assertion to the develop branch, would you like to test?

**Comment by jmsether** [comment]
Sure, I am all for experimentation, but first I would like to just get my copy generating images first. I think crop would be better for preserving the aspect ratio, but both have merits and options are always nice.

**Comment by jmsether** [comment]
I see the commit. I will test it when I am back at my machine in 30sih min

**Comment by jmsether** [comment]
@GeorgLegato I got a new type of error this time

`Error completing request
Arguments: ([[0, 'Cat'], ['1', 'Dog'], [2, 'Happy Pets']], 'ugly', 8, 7, 20, None, None, 30, 0, 0, 0, 1, 0, 2, False, 0, 1, 512, 512, 1, 'Euler a', False, 'None', 1) {}
Traceback (most recent call last):
  File "H:\AUTO 11\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\AUTO 11\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\AUTO 11\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 221, in create_zoom
    result = create_zoom_single(
  File "H:\AUTO 11\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 307, in create_zoom_single
    load_model_from_setting("infzoom_txt2img_model", progress, "Loading Model for txt2img: ")
  File "H:\AUTO 11\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 177, in load_model_from_setting
    raise Exception("This is not a compatible StableDiffusion Platform, can not access checkpoints")
Exception: This is not a compatible StableDiffusion Platform, can not access checkpoints

Traceback (most recent call last):
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f`

It looks like the new point of problem is "Exception: This is not a compatible StableDiffusion Platform, can not access checkpoints"

**Comment by GeorgLegato** [comment]
oh yes, my fault. vlad1111 has fixed an important name in auto1111, so i had to determine which platform we are on 
lemme check

**Comment by GeorgLegato** [comment]
@jmsether I fixed that Platform-Checkpoint-glitch, please try again

**Comment by jmsether** [comment]
@GeorgLegato I work graves so I will check that when I get off of work later tonight.

**Comment by JerryOver** [comment]
> I just realized what was meant by custom init image. And no I am not using one. Should I be?

I wasn't able to get an initial image to work for me. When I left it blank, I got an animation. Here is a Youtube link for the tutorial I followed. https://www.youtube.com/watch?v=PrTcFvu5gHo&t=452s. Start watching at 3:20. He only used square images and suggested starting with 256x256 because you'll get quick results. Meant for you to test it for yourself before you moved onto larger images. He didn't using anything larger than 768x768 because GPU would get overheated. Also you are suppose to use inpainting checkpoints. Realistic Vision and RevAnimated have these. He used a specific VAE, but I just used the default. I hope this helps. Definitely watch the video. It's not very long.

**Comment by v8hid** [comment]
> I wasn't able to get an initial image to work for me.

It's very odd, the first time seeing the initial image not working for someone, create a new issue I try my best to help.
The video is a very good source, I suggest everyone watch it!

**Comment by JerryOver** [comment]
Thanks! I plan on using it very soon. I will do so if the problem continues.

**Comment by JerryOver** [comment]
It still does it. Here's the error I get if I try to include an initial image:

Error completing request
Arguments: ([[0, '((Best quality)), ((masterpiece)),((realistic)),viewer walking on a perfectly straight endless path in a beautiful Japanese Village at springtime, sukura,butterflies,blue sky, scenic, masterpiece'], ['3', '((Best quality)), ((masterpiece)),((realistic)),viewer walking on a perfectly straight endless path in a beautiful Japanese Village at springtime, sukura,butterflies,blue sky, scenic, masterpiece']], 'hallway,indoors,inside,ceiling, doorway,kitsch,ugly,oversaturated, grain, low-res, deformed,blurry,blur,out of focus, poorly  drawn, childish,mangled, old, surreal, text', 5, 7, 50, <PIL.Image.Image image mode=RGB size=512x512 at 0x7FA95B621CA0>, 30, 1, 0, 0, 1, 0, 1, False, 0, 3, 512, 512, 1, 'Euler a') {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py", line 154, in create_zoom
    result = create_zoom_single(
  File "/content/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/scripts/infinite-zoom.py", line 357, in create_zoom_single
    write_video(
  File "/content/stable-diffusion-webui/extensions/infinite-zoom-automatic1111-webui/iz_helpers/video.py", line 35, in write_video
    writer.append_data(np_frame)
  File "/usr/local/lib/python3.9/dist-packages/imageio/core/format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "/usr/local/lib/python3.9/dist-packages/imageio/plugins/ffmpeg.py", line 593, in _append_data
    raise ValueError(
ValueError: All images in a movie should have same number of channels

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 935, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

I use a colab. I don't know if that matters. I can get videos if I don't include an initial image, but I would like to get the initial image part of it working as well.

**Comment by JerryOver** [comment]
Stable Diffusion still finishes the videos even if I get the error. I'm able to get them out of the outputs folder.

**Comment by jmsether** [comment]
Still a no go for me. same error here is error just in case

`Error completing request0:47,  7.74it/s]
Arguments: ([[0, 'a dense forest']], 'out of frame, lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, username, watermark, signature', 8, 7, 20, None, None, 30, 0, 0, 0, 1, 0, 2, False, 0, 1, 512, 512, 1, 'Euler a', False, 'None', 1) {}
Traceback (most recent call last):
  File "H:\AUTO 11\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\AUTO 11\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\AUTO 11\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 242, in create_zoom
    result = create_zoom_single(
  File "H:\AUTO 11\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 478, in create_zoom_single
    write_video(
  File "H:\AUTO 11\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\iz_helpers\video.py", line 36, in write_video
    writer.append_data(np_frame)
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\imageio\core\format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\imageio\plugins\ffmpeg.py", line 591, in _append_data
    raise ValueError("All images in a movie should have same size")
ValueError: All images in a movie should have same size

Traceback (most recent call last):
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "H:\AUTO 11\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f`

**Comment by jmsether** [comment]
@GeorgLegato I decided to remove the check in imageio and I got some very interesting results. The plugin started working but the output was rather weird. Maybe this would shed some light on whats going wrong. It looks like the masks are not being generated correctly though.
![image](https://user-images.githubusercontent.com/5393103/233705071-256d9a36-c1d0-4420-96d1-4c7574f8124e.png)


https://user-images.githubusercontent.com/5393103/233705087-11cd4691-dfb1-4134-989e-4f9602d724dc.mp4

**Comment by GeorgLegato** [comment]
I have seen in the logs, that the init image is being passed by its "data:url:bsae64...", which is due to use a collab.
Locally wen can have a file-uri and processing sees a file from filysystem.
currently both, SD1111 and Vlad1111 completely messed up with pytorch etc. cant test now

**Comment by GeorgLegato** [comment]
checked the img src in local version, it is a data-url not a file urel. so no difference to see

**Comment by jmsether** [comment]
I think I have found the cause of my error @GeorgLegato 

`original frame sizes:  [(512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (1024, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (1024, 512)]
Resized frame sizes:  [(512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512), (512, 512)]`

I will post more shortly when I figure more things out

**Comment by jmsether** [comment]
@GeorgLegato So here are my findings. For whatever reason the last frame being inserted into the array of frames is doubled in width and sometimes we get an odd rounding problem. I got this working but I am still having a wonky result in the output but the output is now working at the very least. How can I get the code to you as I would feel a bit bad pushing my botched code?

**Comment by jmsether** [comment]
I have managed to get a good patch in place to fix the crashing issue that I think will cause minimal problems down the road but I am still stumped on how to fix the off-centered zooming and mask. @GeorgLegato @v8hid any suggestions on where to look in the code base? Here is what I am getting so far.


https://user-images.githubusercontent.com/5393103/233753280-3dd4cf0a-fc34-4f5d-b0b5-e2901513cc5a.mp4

**Comment by v8hid** [comment]
@jmsether dude this is really weird, no one had this issue before. so you should consider checking other things first do you have Discord?

**Comment by jmsether** [comment]
@v8hid I do have discord. I know that I tend to have very random and unique issues show up as my gremlins are very unique by themselves. I would love guidance though on how to troubleshoot this problem so we can get this fixed.

**Comment by v8hid** [comment]
I would love to troubleshoot, so come to discord we can fix it together.
https://discord.gg/gnHpmqsm

**Comment by jmsether** [comment]
I am already there :)

**Comment by jmsether** [comment]
@v8hid Did you want me to open a new thread about this issue? Also, would it be ok to push my fix?

**Comment by jmsether** [comment]
To everyone who finds this post later. I have found the issue and will be implementing a patch for it. The problem was quite simple in the end. If you have "Show grid in results for web" turned on in the user interface under settings it causes stable diffusion to return both the mask and the image side by side.

**Comment by GeorgLegato** [comment]
good job. as far as i ve seen, SD::ProcessImage returns an array of two images: image and mask, and I thought we get only "processed[0]". but ok. its fixed.

**Comment by v8hid** [comment]
Reason of problem: Img2Img was including mask image on the output 

HotFix: unchecking `Show grid in results for web` from webui setting
