### ISSUE TITLE
Getting rid of the frame seam

### ISSUE THREAD

**Issue by v8hid** [v8hid/infinite-zoom-automatic1111-webui#63]
One issue with outpainting an image without a `mask_blur` is that it can result in a noticeable frame around the edges of the image. While using an inpainting model can help to reduce this effect, there may still be instances where the frame is visible or there is a noticeable color shift.
<p  align="center" style="display: inline-block;">
<img src="https://user-images.githubusercontent.com/62482657/234218368-0779d24d-0675-45a0-9652-1a50ad92ccb1.png" width="300" height="300">
</p>
However, using mask_blur presents another challenge - while it can help to create a smoother and more visually appealing outpainted image,
<p  align="center" style="display: inline-block;">
  <img src="https://user-images.githubusercontent.com/62482657/234219622-d9599e6c-2d24-41c5-8f55-c0359152a32e.png" width="300" height="300">
  <img src="https://user-images.githubusercontent.com/62482657/234219883-670fb990-062b-4eb5-ac1e-7cb23a9eca46.png" width="300" height="300">
</p>
In practice, the use of mask_blur can cause some issues with the gradual zoom effect process. This is because the blur effect can slightly remove edges with a margin, leading to potential visual artifacts or inconsistencies in the zoom effect. which something like this:
<p align="center">
<img src="https://user-images.githubusercontent.com/62482657/234223072-1dcf6f77-f42d-45e5-b6ef-de6539658e3d.png" width="300" height="300">
</div>

The possible solution I came up with is to crop the initial image from the second generated image and replace the first frame with it. And repeat it for every iteration.

**Comment by Oncorporation** [comment]
I was considering if a alpha mask might help:
`from PIL import Image

# Load the original image and the mask
original_image = Image.open('path/to/original_image.jpg')
mask_image = Image.open('path/to/mask_image.png').convert('L')  # convert to grayscale

# Resize the mask to match the original image size
mask_image = mask_image.resize(original_image.size)

# Apply the mask as the alpha layer of the original image
result_image = original_image.copy()
result_image.putalpha(mask_image)

# Save the result image
result_image.save('path/to/result_image.png')`

We could choose the mask and have it gradually apply an alpha as opposed to cropping

**Comment by GeorgLegato** [comment]
good point is, we can test this manually in img2img. so it has not to be coded to have a proof

**Comment by v8hid** [comment]
fixed in #76
