### ISSUE TITLE
Infinite Zoom's ValueError Issue

### ISSUE THREAD

**Issue by Davinci-Mich** [v8hid/infinite-zoom-automatic1111-webui#64]
![image](https://user-images.githubusercontent.com/131768558/234258217-c4d9d7e0-8b4e-451e-a073-b5542c40500f.png)
![image2](https://user-images.githubusercontent.com/131768558/234258213-02422b73-4185-4b0a-bc14-7eae92e5cbb6.png)

If you encounter a ValueError while using Infinite Zoom to generate, as shown in the screenshot, it could be due to insufficient VRAM. You can solve this issue by following these steps: add --xformers --medvram after COMMANDLINE_ARGS= in your Launch.bat file：

set COMMANDLINE_ARGS= --xformers --medvram

By doing this, you will reduce the VRAM usage, allowing the generation process to proceed smoothly. However, it may take longer than before.

This may seem like a minor issue, but once it occurs, it can cause the entire Stable Diffusion process to become paralyzed until you restart it. Therefore, if you don't have a large amount of VRAM, you can use the aforementioned method to reduce its usage during generation.

**Comment by v8hid** [comment]
You can also use:

**Comment by v8hid** [comment]
You can also use:
set COMMANDLINE_ARGS= --lowvram
