### ISSUE TITLE
High gpu usage when UI is open and processing?

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [v8hid/infinite-zoom-automatic1111-webui#66]
Whenever I have chrome open and infinite zoom is processing GPU load specifically shoots up like crazy. However if I minify a1111 chrome window a lot of usage drops and processing is working as it should. I noticed this only happening with infinite zoom. 

This is weird, I'm assuming some kind of UI reporting code is written in a blocking way?

**Comment by GeorgLegato** [comment]
could you try to reproduce while having dev-tools opened and capture a "performance" run ?
there is a graphical representation of what has taken how much time.
thanks

**Comment by GeorgLegato** [comment]
https://www.debugbear.com/blog/devtools-performance#:~:text=Profiling%20Site%20Speed%20With%20The%20Chrome%20DevTools%20Performance,Web%20Vitals%20and%20other%20timings%20...%20Weitere%20Elemente
