### ISSUE TITLE
cant install extension

### ISSUE THREAD

**Issue by demirklvc** [v8hid/infinite-zoom-automatic1111-webui#67]
Launching Web UI with arguments: --disable-safe-unpickle --xformers
Error loading script: infinite-zoom.py
Traceback (most recent call last):
  File "C:\Users\RTX01\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\RTX01\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\RTX01\stable-diffusion-webui\extensions\infinite-zoom-automatic1111-webui\scripts\infinite-zoom.py", line 23, in <module>
    from scripts import postprocessing_upscale
ImportError: cannot import name 'postprocessing_upscale' from 'scripts' (unknown location)

**Comment by GeorgLegato** [comment]
check your version of SD-webui.we had once this error and the user had an ancient version.
often people change their "webui-user.bat" and do not 'git commit", so "git pull" wont never update your whole sd-webui-installation (which is ... kinda a stupid and tricky for non-dev-users

**Comment by illtellyoulater** [comment]
having the same problem here, updated sd-webui to latest commit

EDIT:
The only way to fix this was deleting the `venv` and then letting webui.sh build it again.
For those who don't know how to do this: just delete the venv dir (within the sd-webui path) and then run `webui.sh` (or webui.bat, if you are on windows) like normal. This will cause the venv to be rebuilt.
