### ISSUE TITLE
How to set duration? and fix boxes and frames showing?

### ISSUE THREAD

**Issue by Tobe2d** [v8hid/infinite-zoom-automatic1111-webui#7]
How to set duration?

I try adding extra prompts and add 0, 75, 125 etc..  but it gets ignored and same exact duration stay no matter how many prompt i add.

The other question is why am I getting boxes without smooth inpaint? I am using offical SD 1.5 inpainting model.

sample below:
https://user-images.githubusercontent.com/4099839/232152364-b41ac254-a29a-4bdc-a14a-6f4c1b2f614a.mp4

2nd sample:
https://user-images.githubusercontent.com/4099839/232153736-97fe50d8-d037-4844-9500-819f73f0037d.mp4

**Comment by v8hid** [comment]
Hello @Tobe2d,

To improve your results and avoid getting frames, I suggest using inpainting models and setting `mask_blur` to 0.

About outpainting steps, you can use prompts to guide the generation process. For example, you can enter
``` 
+----------------+------------+
| outpaint steps |   prompt   |
+----------------+------------+
|        0       |   prompt1  |
+----------------+------------+
|        3       |   prompt2  |
+----------------+------------+

```

This means that the program will generate the first three outpainting steps using "prompt1" and then switch to "prompt2" for the remaining steps.

I hope this explanation is helpful to you. Let me know if you have any further questions or concerns.
