### ISSUE TITLE
Addition of watermark

### ISSUE THREAD

**Issue by GivenChief** [v8hid/infinite-zoom-automatic1111-webui#70]
Is it possible to add a field with settings to overlay a transparent png-file like a watermark? With the ability to adjust the position (centre, top corner, diagonal)? Instead of editing in video editors.

**Comment by v8hid** [comment]
It is possible but we are not planning to add it for now!

**Comment by GeorgLegato** [comment]
if we do , let us have an RGB-alpha image which is simply pasted into each frame. So we avoid Text/edit etc.
User provides an PNG, size and position, the we are ready.
But as @v8hid told, we have several other issues, esp, softer rendering pipeline
