### ISSUE TITLE
Defaults prompts were broken after recent update.

### ISSUE THREAD

**Issue by BlastedRemnants** [v8hid/infinite-zoom-automatic1111-webui#71]
Hi folks, sorry if I'm doing this wrong but I noticed that after a recent update my default prompts box was showing an error and telling me to check the settings. In the settings menu the default prompt was all on one long line and had some Loras and a bunch of other stuff in it, so I copied the example prompts from your Wiki page into the prompt boxes, exported them, and then copied them neatly into the settings menu as new defaults and sort of tidied it all up a bit. I closed everything and relaunched, and it works perfectly now.

I'm not sure if I'm the only one having this problem, but if anyone is interested here is how I setup the defaults in the settings menu, maybe it will help anyone else with the same problem. I wasn't sure about where to put the linebreaks so I just did it however, probably isn't quite proper but it works now  :D  I did lose the default negative somehow tho, sorry. Oh by the way, is there any way to add the number of steps to the default options menu, or have it exported with saved prompts? I tried sticking a "20" in there in a few different places but it didn't work lol.
Edit: When I pasted it into here it seems to have messed up the indents and stuff, no idea how to fix that sorry! Looks good while I'm editing and then gets flattened out when I'm done, gross lol

{"prompts":
  {"data":
    [
      [0,"jungle with lush green trees and clear blue sky"],
      ["5","jungle with tall brown trees and orange sunset sky"],
      ["10","jungle with sparse trees and dark stormy sky"],
      ["15","jungle with yellow autumn trees and purple twilight sky"]
    ],
    "headers":
    ["Steps","Prompts"]
  },
  "negPrompt":
  "blur, blurry, split frame, drawing, painting, illustration, sketch, watermark, logo, monochrome"
}

**Comment by GeorgLegato** [comment]
just export the Invalid settings table to see how the new syntax shall look like
new fields are commonPromptPrefix and Sufix

**Comment by GeorgLegato** [comment]
here is an example prompt (schema version 1.1). paste it to your Settings->InfZoom and modify to your needs
{
  "prompts": {
    "data": [
      [
        0,
        "Step 0"
      ],
      [
        "5",
        "Step 5"
      ],
      [
        "10",
        "Step 10 etc..."
      ]
    ],
    "headers": [
      "outpaint steps",
      "prompt",
      "img"
    ]
  },
  "negPrompt": "Negative prompt for all steps",
  "commonPromptPrefix": "My common things before each step",
  "commonPromptSuffix": "Prompt behind each step"
}

**Comment by BlastedRemnants** [comment]
Thanks a lot! That's a good bit tidier looking and easier to manage in the settings menu, previously it was all on one long line which was much harder to read. Much obliged friend  :D
