### ISSUE TITLE
[BUG] - Missing .dll files

### ISSUE THREAD

**Issue by GiusTex** [v8hid/infinite-zoom-automatic1111-webui#77]
**Describe the bug**
The program can't generate the video, I keep getting missing .ddl files, and when I download them I get new missing ones. No errors in console. I also added the path to the executables (ffmpeg.exe, ecc).

**To Reproduce**
1. Start generating the video.
2. I get the inpainted image, but not the video.

**Screenshots of error**
No errors in console, just missing files (there were other ones too, but I downloaded them...).
![image](https://user-images.githubusercontent.com/112352961/235481889-8efaefb1-f051-4d81-ab28-0577ae6f8c78.png)![image](https://user-images.githubusercontent.com/112352961/235481919-364b8d2a-8018-4dca-a950-45e4da5dfdcb.png)
![image](https://user-images.githubusercontent.com/112352961/235481944-c1cd611c-d177-49c9-b745-4a884de22d0a.png)![image](https://user-images.githubusercontent.com/112352961/235481965-6e7b5e60-908c-4146-ba64-bad7d50e014d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**
I had this problem even before the main webui update, so I don't think is a torch 2.0.0 or something else error.

**Comment by GeorgLegato** [comment]
Goto Settings and set the Path to your FFMPEG-installation (where ffprobe is located)
maybe download it before
![image](https://user-images.githubusercontent.com/7210708/235487474-1aa99c70-aaba-46c6-8c36-b097a81fe059.png)

**Comment by GeorgLegato** [comment]
my ffmpeg folder looks different, everything statical compiled (no dlls at all)
![image](https://user-images.githubusercontent.com/7210708/235530165-7ac4c600-c0ba-429e-ba35-2d3d90f98b10.png)
loading DLLs is not trivial, esp when through differerent processes (python calls ffmpeg; not sure aboud LD_LIBRARY_PATH stuff etc)
try to download a static compiled version

**Comment by GeorgLegato** [comment]
you got the shared one, I think
![image](https://user-images.githubusercontent.com/7210708/235530537-47d5933b-4583-40b6-8cf3-cf90919f9324.png)

**Comment by GiusTex** [comment]
Yes, that one

**Comment by GiusTex** [comment]
Of course

**Comment by GeorgLegato** [comment]
please try the larger compiles version of ffmpeg

**Comment by GiusTex** [comment]
Same error.
New, bigger folder:
![image](https://user-images.githubusercontent.com/112352961/235639280-bcfd0d27-de38-44dc-a5e2-bbe233b701b4.png)
![image](https://user-images.githubusercontent.com/112352961/235639490-077a0d96-f105-41c5-a7d6-c60e2f9becf8.png)
![image](https://user-images.githubusercontent.com/112352961/235639569-cf4f0e8e-af96-480a-83ba-9d7715c988ba.png)
Video + error:
![image](https://user-images.githubusercontent.com/112352961/235639599-c37e8994-fb79-43e8-873f-6c019bab527b.png)
![image](https://user-images.githubusercontent.com/112352961/235639729-cb1a6334-0862-48ed-a92d-0385e6ea0694.png)

**Comment by GeorgLegato** [comment]
so, actually nothing changed. that means some other ffmpeg installation is prior to that what you downloaded and set to our Settings.
* open command line and type
``` echo %PATH%```

I assume there is some entry, pointing to a broken? ffmpeg installation

**Comment by GiusTex** [comment]
I have another extension that uses ffmpeg, [training picker](https://github.com/Maurdekye/training-picker) I think (that too worked gaving some errors), tomorrow when I'm at my computer I'll try echo %PATH%

**Comment by GiusTex** [comment]
I had in C:\Windows\System32 a copy of the old executables (ffmpeg, probe and play), deleting them forced the webui to finally use the path with the new files, and no more errors
