### ISSUE TITLE
I added SendtoPanoramaViewer button, need higher resolution

### ISSUE THREAD

**Issue by GeorgLegato** [v8hid/infinite-zoom-automatic1111-webui#8]
The InfZoom Extension is nice to create panorama videos, when using a 360-panorama-LORA or just prompt "360 full panorama view"
My extension has a 360-panorama-viewer integrated and I added a sento-button, see screenshot.

360 Panoramas need much resolution. Is there an UI-setting planned to setup resolution? and or include an upscaler? nice if details could be added while upscaling.

https://github.com/GeorgLegato/sd-webui-panorama-viewer

![image](https://user-images.githubusercontent.com/7210708/232170814-f72153ff-e82a-4670-bc6c-3b24c151c203.png)

**Comment by GeorgLegato** [comment]
update:
360 panorama movie viewer opens now next to the 2dmovie player
![image](https://user-images.githubusercontent.com/7210708/232179197-49ee558a-d7b6-4592-9e09-302bbf0b57ee.png)
We need MORE PIXELS :-))

**Comment by v8hid** [comment]
Hi @GeorgLegato,

I wanted to express my appreciation for your cool extension - it definitely caught my eye! I'm considering implementing the send-to button, but before that, I need to implement upscaling. However, as a bit of a one-man team, I'm finding it challenging to tackle everything alone.

I was wondering if you would be willing to contribute and lend a hand? Your expertise and assistance would be greatly appreciated in moving this project forward. Let me know if you're interested, and we can discuss further details.

**Comment by GeorgLegato** [comment]
i have just tested by tweaking your python to setup 1280x1280 px. this works. as of now the ratio has to be 1:1
Upscaling would be great and for for 360 panos controlnet.. 
but that makes me think, this extension should work (as well) as a script from inside img2img, then everthing is already setup: scale, controlnet etc

**Comment by GeorgLegato** [comment]
@v8hid I have it in my pipeline.
pullrequest incoming
https://www.reddit.com/r/StableDiffusion/comments/12npykg/preview_infinitezoom360panoramamovie_high_res/

**Comment by v8hid** [comment]
> @v8hid I have it in my pipeline. pullrequest incoming https://www.reddit.com/r/StableDiffusion/comments/12npykg/preview_infinitezoom360panoramamovie_high_res/

Sorry, I just noticed this comment.
It is really cool, we can add it in a different branch for now.
