### ISSUE TITLE
Automatic 1111 WebUI Extension is missing after latest update

### ISSUE THREAD

**Issue by FunkyPhilVR** [v8hid/infinite-zoom-automatic1111-webui#82]
As the title suggests, the Automatic 1111 WebUI Extension for Infinite Zoom is missing after I updated it. I used it yesterday for many hours. No problems. The update has caused some sort of issue. I still see Infinite Zoom in my extensions folder and it is active but the tab is nowhere to be found.  I reinstalled Infinite Zoom and restarted "webui-user.bat". It did not make a difference. Any solutions or a way to rollback to the previous version?
 
 - OS: Windows 10
 - Version 22H2
 - Automatic 1111 running in Google Chrome browser
 
![new capture web ui 1111](https://user-images.githubusercontent.com/97666703/235731668-78d10710-4ced-46f7-afa5-de94e45caa6d.JPG)

**Comment by FunkyPhilVR** [comment]
Just double checked. As a matter of fact there is! I'm just not sure how to fix it.
![error inf zoom](https://user-images.githubusercontent.com/97666703/235739635-5c838e38-0c69-47fa-bd3e-d5e6a1190345.JPG)

**Comment by dogederp** [comment]
I downloaded the extention about 3 hours ago and had the same error, but updating the Automatic1111 WebUI fixed it for me.

**Comment by v8hid** [comment]
> but updating the Automatic1111 WebUI fixed it for me.

@FunkyPhilVR looks like updating webui will fix the issue.

**Comment by FunkyPhilVR** [comment]
I did a fresh install and it's working now. thanks!
