### ISSUE TITLE
Corrupted Json structure

### ISSUE THREAD

**Issue by Tobe2d** [v8hid/infinite-zoom-automatic1111-webui#88]
I see some warrning in the log as showing below:

```
Infinite Zoom: Corrupted Json structure: {
    "prompts":{
       ...

```

I try removing the extention and installing again and I still get the same warrning

**Comment by GeorgLegato** [comment]
click on "export prompts", open the file you get downloaded and copy/paste the content into "Settings->InfiniteZoom->Json-Start-Code". You will see how to provide a valid json for initial table on starting StableDiff.
or you take this one for example:

```
{
  "prompts": {
    "data": [
      [
        0,
        "Huge spectacular Waterfall in a dense tropical forest,epic perspective,(vegetation overgrowth:1.3)(intricate, ornamentation:1.1),(baroque:1.1), fantasy, (realistic:1) digital painting , (magical,mystical:1.2) , (wide angle shot:1.4), (landscape composed:1.2)(medieval:1.1), divine,cinematic,(tropical forest:1.4),(river:1.3)mythology,india, volumetric lighting, Hindu ,epic"
      ]
    ]
  },
  "negPrompt": "frames, border, edges, borderline, text, character, duplicate, error, out of frame, watermark, low quality, ugly, deformed, blur, bad-artist",
  "prePrompt": "<lora:epiNoiseoffset_v2:0.6> ",
  "postPrompt": "style by Alex Horley Wenjun Lin greg rutkowski Ruan Jia (Wayne Barlowe:1.2)"
}
```

**Comment by GeorgLegato** [comment]
> I see some warrning in the log as showing below:
> 
> ```
> Infinite Zoom: Corrupted Json structure: {
>     "prompts":{
>        ...
> ```
> 
> I try removing the extention and installing again and I still get the same warrning

exactly where "..." would follow is the answer. the json is not valid. but not visible to debug

**Comment by Tobe2d** [comment]
Thanks that solved it. 

now the question, is this only for me or it came with the install from the repo itself?

as I haven't used it since I installed it.

**Comment by GeorgLegato** [comment]
json format has evolved 2-3 times, maybe you had one old intermediate syntax in your setttings
