### ISSUE TITLE
Executable 'ffprobe' not found - FFPROBE PATH not set

### ISSUE THREAD

**Issue by v8hid** [v8hid/infinite-zoom-automatic1111-webui#9]
I have the same problem and found some manual workaround; if not solution.
My setup is Windows, SD is latest version (22bcc or so)

ffrpobe is still not found.
I "pip install ffprobe", did not help.
The pyffprobe is only a wrapper for some ffprope.exe, which has to be
* available on disk
* and in ENV:PATH

So, I downloaded from github latest ffmpeg release (https://github.com/BtbN/FFmpeg-Builds/releases) and 
upacked somewhere.
Now, you need to extend the PATH variable in the context where you SD-Webui is started; either manually
`set PATH=%PATH%;C:\Users\YOU\Downloads\ffmpeg-master-latest-win64-gpl\bin`

Pros put that in their web-user.bat...

@v8hid You could solve that more elegant by provide a Settings-property "PathToFFMPEG" and set OS.Path accordingly

_Originally posted by @GeorgLegato in https://github.com/v8hid/infinite-zoom-automatic1111-webui/issues/3#issuecomment-1509216353_

**Comment by nicholassun99** [comment]
Hi, I am the guy who got the error in Issue 3. I manage to fix the error by including the path to the **ffprobe executable**. Setting the path to the bin directory containing the executable did not work for me.
