### ISSUE TITLE
[BUG] Black and white, greyscale, output.

### ISSUE THREAD

**Issue by TripleHeadedMonkey** [v8hid/infinite-zoom-automatic1111-webui#91]
**Describe the bug**
Everything I generate using the extension after updating both SD and IZ comes out greyscale. The first generation is in colour but from then onwards they are all black and white for some reason. I've tried prompting against this and using various different options but I can't seem to get this to change.

**To Reproduce**
1. Enter these inputs 'default settings'
2. Click on 'generate'

**Expected behavior**
I expect it to return colour generations
![00117-4151439096](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/fbcc69ca-d48a-4b3a-8211-a670d2992cef)
![00116-2360376342](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/1f17d96f-a88b-4275-a6a7-3cdb497c3342)
![00115-4161850973](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/c8baa607-0b52-4735-9da5-61b64d7cb97f)
![00114-93780385](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/869aeac8-fc00-45a6-a446-e70d3c50af5b)
![00128-152265124](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/434fea5b-5d0b-4661-8e0d-f7a1cde272de)
![00127-1485996145](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/753d6545-da97-430e-a1f7-c309c436e02f)
![00126-696266321](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/3ba0a8d3-1779-40da-9bf7-ca83999892b8)
![00125-2427738626](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/3b13eaa2-8607-405d-ad26-a9a53ba1cf63)
![00124-534173332](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/a0381041-7b1b-40cc-872b-944ae916fc95)
![00123-2273294670](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/345e84bc-9faa-424a-bb61-f08a19dbd77d)
![00122-986330514](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/0a08c262-ad2d-49e2-a7b5-6e52371043d1)
![00121-3068886698](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/e7b35af8-a4ef-4bbf-90ab-d6c02e9b4444)
![00120-200932254](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/11ebcf20-4fb6-48fc-82d4-ef2541c553a4)
![00119-2787724367](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/2dce50a8-9317-464c-89f0-fd2946ca9916)
![00118-3522215237](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/99692883/4fc10056-12de-45db-9bc0-7441dbf68100)
**Screenshots of error**
If applicable, add screenshots to help explain your problem. Or just dump the error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2

**Additional context**

**Comment by TripleHeadedMonkey** [comment]
Also thought I should mention that I really appreciate the work you've done here. Great extension, perhaps one of the best when functioning as intended!

**Comment by v8hid** [comment]
Hello @TripleHeadedMonkey, read https://github.com/v8hid/infinite-zoom-automatic1111-webui/wiki/Recommended-settings
After you made sure that your settings are right, try a different model and different sampler like Euler A. If the problem persists let me know!

**Comment by TripleHeadedMonkey** [comment]
Sorry about the slow response. It was colour correction. You solved my issue. Thanks for the help and sorry to waste your time with what turned out to be basic questions xD
