### ISSUE TITLE
[BUG]ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4)

### ISSUE THREAD

**Issue by cgd199158** [v8hid/infinite-zoom-automatic1111-webui#96]
**Describe the bug**
when i create a vieo is error;
```
Traceback (most recent call last):
  File "/Users/cgd/cgd/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/cgd/cgd/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1318, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/cgd/cgd/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1221, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/Users/cgd/cgd/ai/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1196, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4)
```

**To Reproduce**

**Expected behavior**

**Screenshots of error**

**Desktop (please complete the following information):**
<img width="834" alt="image" src="https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/18514077/08eaf75a-c86f-4e92-b07a-b8f55f82c42a">
<img width="650" alt="image" src="https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/18514077/78196e8b-76bd-47db-92a9-1bc1fd1253b7">
<img width="2507" alt="image" src="https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/18514077/9eea5fb5-d87e-4cb2-a851-ee98532d928d">

**Additional context**

**Comment by GeorgLegato** [comment]
90% of all bug reports cutting off the interesting part of the error log.
the 5-10 lines just before "Traceback" will give us information what causes the prob

**Comment by cgd199158** [comment]
> 

<img width="834" alt="image" src="https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/18514077/9b435b9e-7a87-4162-9dcf-cdafed152caa">

**Comment by GeorgLegato** [comment]
goto Settings -> InfiniteZoom and there check the given URL, where you download the FFMPEG binaries. Unzip them to your favorite location and named that path in the Settings-Toolbox
