### ISSUE TITLE
TiffWriter.write() got an unexpected keyword argument 'fps'[BUG]

### ISSUE THREAD

**Issue by jluF** [v8hid/infinite-zoom-automatic1111-webui#99]
**Describe the bug**
This bug appears after I finish drawing the picture, how to solve it

**To Reproduce**

**Expected behavior**

**Screenshots of error**
![image](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/32354851/ccc1de4a-e78a-401d-be52-3f5ea6bcba81)

**Desktop (please complete the following information):**

**Additional context**

**Comment by jluF** [comment]
I restart the webui and, the problem has been solved...
quite strange, but just fine.

**Comment by py727** [comment]
![Snipaste_2023-07-05_23-11-55](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/138693703/330b3396-5851-4b03-93fd-f8784bea3a97)
me too

**Comment by py727** [comment]
![Snipaste_2023-07-05_23-12-53](https://github.com/v8hid/infinite-zoom-automatic1111-webui/assets/138693703/a9477055-a229-4665-a944-b54dadacbbdc)
